steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pse-frontend', '--build-arg', 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/pse-frontend'
substitutions:
  _VITE_API_BASE_URL: ''
